#!/bin/sh

# Reference all jar files
# params:

export jar_name="./lib/*:./canova.jar"
export main_class_name="org.canova.cli.driver.CommandLineInterfaceDriver"

export params=""

for i in $*;
do
    export params="$params $i"
done

echo $params
java -cp "$jar_name" "$main_class_name" $params


printf '\n\n'
